# Site settings
title: Dabobroto Sarkar's CV 
description: Dabobroto Sarkar's CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: https://dstushar7.github.io/resumecard
rss_url: 
google_analytics: 'G-XSZLGGZ043'

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Dabobroto Sarkar
  title: Computer Science Graduate
  address: Sutrapur, Dhaka
  email: u1504048@student.cuet.ac.bd
  link: https://dstushar.github.io
  weibo:
  github: dstushar7
  linkedin: dabobroto-sarkar
  facebook: debu.tushar
#  twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
#  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: BFIN IT PVT Ltd.
      location: Dhaka, Bangladesh
      title: Intern
      started: 2019
      duration: (August 2019 - September 2019)
      description: BFIN IT PVT LTD is a French Financial management & accounting software provider (IFRS - GAAP) to SME & large business worldwide. I worked as an Interne there from August 2019 to September 2019
    # - work2:
    #   company: XXX Ltd
    #   location: Shanghai, China
    #   title: Java Developer
    #   started: 2012
    #   duration: (2012 - 2014)
    #   description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    # - work3:
    #   company: XXX Ltd
    #   location: Shanghai, China
    #   title: Java Developer
    #   started: 2009
    #   duration: (2009 - 2012)
    #   description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Chittagong University of Engineering & Technology
      location: Chattogram, Bangladesh
      degree: B.Sc
      major: Computer Science & Engineering
      started: 2015
      duration: (2015 - 2021)
      description: It is a well reputated public university in Bangladesh. It has a friendly environment. I graduated from this university in 2021 with GPA 3.01 
    - education2:
      organization: Notre Dame College, Dhaka
      location: Dhaka, Bangladesh
      degree: HSC
      major: Science
      started: 2013
      duration: (2013 - 2015)
      description: It is a well reputated college in Bangladesh. I got GPA 5.00 from this college in HSC
    - education3:
      organization: Dhaka Collegiate School, Dhaka
      location: Dhaka, Bangladesh
      degree: SSC
      major: Science
      started: 2004
      duration: (2004 - 2013)
      description: This is the oldest school in Dhaka. I got GPA 5.00 from this school in SSC.
  languages:
    - language1:
      name: Bangla
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    # - language3:
    #   name: Japanese
    #   proficiency: Limit
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: HTML
      percentage: 90%
    - skill3:
      name: Bootstrap
      percentage: 70%
    - skill4:
      name: C++
      percentage: 30%
    - skill5:
      name: Java/Java EE
      percentage: 20%
